---
- include_tasks: plex.yml
  when: (ansible_os_family == 'RedHat') or
        (ansible_os_family == 'Debian')

- name: Include wilmardo.tautulli
  include_role:
    name: wilmardo.ansible_role_tautulli
  when: tautulli_install

- name: Include wilmardo.plexupdate
  include_role:
    name: wilmardo.plexupdate
  when: plexupdate_install
